name: docker push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history (optional; set 1 if you only need HEAD)

      - name: Verify build context
        run: |
          pwd
          ls -la
          test -d .git && echo ".git present" || (echo "no .git" && exit 1)
          cat .dockerignore || echo "no .dockerignore"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: juggy69/pushworld:amd
